### PR TITLE
Pass current hash to load to avoid reloading the current model

### PR DESCRIPTION
**Pull request by marcusklaas**
Addresses https://github.com/vaitech/Velox/issues/2. Resolves the issue for me.

### CODE REVIEW

**Comment by marcusklaas** [comment]
Oops - forgot to run the tests. I'll see what's going on there.

**Comment by marcusklaas** [comment]
Hmmm, the tests that are failing on Travis are passing for me locally..

**Comment by lukedeo** [comment]
Hmm thats is weird, wha tsystem are you running on?

**Comment by marcusklaas** [comment]
I installed `moto`, as suggested in readme. Is that what you meant?

**Comment by lukedeo** [comment]
Thanks for finding this, @marcusklaas! This has been fixed in https://github.com/vaitech/Velox/commit/1a065b900d864784dba18e9c011b3bfba2857a6c. Though the PR was not merged, your additions were added in addition to other improvements around this issue. Thanks for your contribution 👍

**Pull request closed without merging**
